sudo: false
dist: trusty

language: python
python:
  - '3.6'

cache: pip

# As of 2017-08 the new travis trusty images have broken postgis,
# so we have to specify the exact postgres version to install right addons
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

install: 'pip install codecov -r requirements.txt -r requirements-dev.txt'

before_script:
  - psql -c 'create database kaavapino;' -U postgres
  - psql -U postgres -c "create extension postgis"

script:
  - flake8
  - black --check .
  - pytest -ra -vvv --cov

after_success: codecov

env:
  - SECRET_KEY=topsecret123 DATABASE_URL="postgis://postgres:@localhost/kaavapino"
